/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'project' 
 * Target:  'Target 1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "max32665.h"

/* ARM::CMSIS-View:Event Recorder&DAP@1.6.0 */
#define RTE_CMSIS_View_EventRecorder
        #define RTE_CMSIS_View_EventRecorder_DAP
/* ARM::CMSIS:RTOS2:Keil RTX5&Library@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
        #define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
/* Keil::CMSIS Driver:I2C:Multi-Slave@1.0.1 */
#define RTE_Drivers_I2C_MultiSlave      /* Driver I2C Multi-Slave */
/* Keil::CMSIS Driver:NAND:Memory Bus@1.1.0 */
#define RTE_Driver_NAND_MemoryBus       /* Driver NAND Flash on Memory Bus */
/* Keil::CMSIS Driver:SPI:Multi-Slave@1.0.1 */
#define RTE_Drivers_SPI_MultiSlave      /* Driver SPI Multi-Slave */
/* Maxim::BSP&MAX32665 BSP:EvKit V1@1.1.0 */
#define BOARD EvKit_V1 /* Target Board */


#endif /* RTE_COMPONENTS_H */
