/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'pro3' 
 * Target:  'Target 1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "max32665.h"

/* Maxim::BSP&MAX32665 BSP:EvKit V1@1.1.0 */
#define BOARD EvKit_V1 /* Target Board */


#endif /* RTE_COMPONENTS_H */
